version: 0.2

phases:
  build:
    commands:
      - cd dev
      - terraform init 
      - terraform apply -input=false -auto-approve

  post_build:
    commands:
      - echo "Terraform completed on `date`"

artifacts:
  files:
    - '**/*'
