version: 0.2

phases:
  install:
    commands:
      - pwd
      - yum -y update
      - yum -y groupinstall "Development Tools"
      - yum -y install openssl-devel bzip2-devel libffi-devel xz-devel
      - yum -y install wget unzip curl
      - wget https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz
      - tar xvf Python-3.10.0.tgz
      - cd Python-3.10*/
      - ./configure --enable-optimizations
      - make altinstall
      - pip3 install boto3
      - wget https://releases.hashicorp.com/terraform/1.0.2/terraform_1.0.2_linux_amd64.zip
      - unzip terraform_1.0.2_linux_amd64.zip
      - mv terraform /bin
      - cd ..
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
  build:
    commands:
      - pwd
      - aws configure set aws_access_key_id Supritha-at-361256272604
      - aws configure set aws_secret_access_key e9cLUHdxkTWs1K0kHvbvs3x2LYrHqjJ5A2+y+ZQa53c=
      - cd "$dirname"
      - terraform --version
      - terraform init 
      - terraform apply -input=false -auto-approve

  post_build:
    commands:
      - echo "Terraform completed on `date`"

